__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  '../base/dataloader.yml',
  '../base/optimizer.yml',
  '../base/rtv4_hgnetv2.yml',
  '../base/rtv4.yml'
]

output_dir: ./outputs/rtv4_hgnetv2_s_coco

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*bn).*$'
      lr: 0.0002
    -
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0004
  betas: [0.9, 0.999]
  weight_decay: 0.0001


epoches: 132

flat_epoch: 64
no_aug_epoch: 12

train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: [4, 64, 120]

  collate_fn:
    mixup_epochs: [4, 64]
    stop_epoch: 120
